"""Activity model - Official v1 Contract"""
import enum
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, DateTime, Text, ForeignKey, CheckConstraint, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.models.base import BaseModel


class ExecutionState(str, enum.Enum):
    """Execution states for activities - MUST match mobile exactly"""
    PENDIENTE = "PENDIENTE"
    EN_CURSO = "EN_CURSO"
    REVISION_PENDIENTE = "REVISION_PENDIENTE"
    COMPLETADA = "COMPLETADA"


class Activity(BaseModel):
    """
    Activity model - Official v1 specification
    
    This is the SOURCE OF TRUTH for sync operations.
    Mobile and backend MUST use identical field definitions.
    
    KEY DECISIONS:
    - uuid: Generated by mobile, used for idempotency
    - server_id: Backend autoincrement (id field)
    - pk_start/pk_end: integers in METERS (not "km+mmm" strings)
    - execution_state: string enum (not int)
    - sync_version: monotonic increment for pull sync
    """
    __tablename__ = "activities"
    
    # ============================================================
    # IDENTITY FIELDS (Critical for sync)
    # ============================================================
    id = Column(Integer, primary_key=True, autoincrement=True)  # server_id
    uuid = Column(UUID(as_uuid=True), unique=True, nullable=False, index=True)
    
    # ============================================================
    # SYNC FIELDS
    # ============================================================
    sync_version = Column(Integer, nullable=False, default=0, index=True)
    # Note: created_at, updated_at come from BaseModel
    deleted_at = Column(DateTime, nullable=True, index=True)  # Soft delete
    
    # ============================================================
    # TERRITORIAL CONTEXT
    # ============================================================
    project_id = Column(String(10), ForeignKey("projects.id"), nullable=False, index=True)
    front_id = Column(UUID(as_uuid=True), ForeignKey("fronts.id"), nullable=True, index=True)  # nullable for "general"
    
    # PK (Progresiva Kilométrica) in METERS
    pk_start = Column(Integer, nullable=False, index=True)  # Example: km 142+000 → 142000
    pk_end = Column(Integer, nullable=True)  # Nullable for point (puntual), required for segment (tramo)
    
    # ============================================================
    # WORKFLOW STATE
    # ============================================================
    execution_state = Column(
        String(20),
        nullable=False,
        default=ExecutionState.PENDIENTE.value,
        index=True
    )
    
    # ============================================================
    # ASSIGNMENT
    # ============================================================
    assigned_to_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True, index=True)
    created_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    
    # ============================================================
    # ACTIVITY TYPE & METADATA (catalog-driven)
    # ============================================================
    catalog_version_id = Column(UUID(as_uuid=True), ForeignKey("catalog_versions.id"), nullable=False)
    activity_type_code = Column(String(20), nullable=False)  # e.g., "INSP_CIVIL", "ASAMBLEA"
    
    # Location details
    latitude = Column(String(20), nullable=True)  # Decimal degrees as string for precision
    longitude = Column(String(20), nullable=True)
    
    # Title and description
    title = Column(String(200), nullable=True)
    description = Column(Text, nullable=True)
    
    # ============================================================
    # RELATIONSHIPS
    # ============================================================
    project = relationship("Project", foreign_keys=[project_id])
    front = relationship("Front", foreign_keys=[front_id])
    assigned_to = relationship("User", foreign_keys=[assigned_to_user_id])
    created_by = relationship("User", foreign_keys=[created_by_user_id])
    catalog_version = relationship("CatalogVersion", foreign_keys=[catalog_version_id])
    
    # ============================================================
    # CONSTRAINTS
    # ============================================================
    __table_args__ = (
        CheckConstraint('pk_end IS NULL OR pk_end >= pk_start', name='check_pk_range'),
        CheckConstraint(
            f"execution_state IN ('{ExecutionState.PENDIENTE.value}', "
            f"'{ExecutionState.EN_CURSO.value}', "
            f"'{ExecutionState.REVISION_PENDIENTE.value}', "
            f"'{ExecutionState.COMPLETADA.value}')",
            name='check_execution_state'
        ),
        Index('idx_activity_sync', 'sync_version', 'updated_at'),
        Index('idx_activity_project_front', 'project_id', 'front_id'),
        Index('idx_activity_pk_range', 'pk_start', 'pk_end'),
    )
    
    def __repr__(self):
        return f"<Activity {self.uuid} [{self.execution_state}] PK{self.pk_start}-{self.pk_end or self.pk_start}>"
    
    def increment_sync_version(self):
        """Increment sync_version when activity is modified"""
        self.sync_version += 1
    
    def is_deleted(self) -> bool:
        """Check if activity is soft-deleted"""
        return self.deleted_at is not None
    
    def soft_delete(self):
        """Soft delete this activity"""
        self.deleted_at = datetime.now(timezone.utc)
        self.increment_sync_version()
    
    def to_sync_dict(self) -> dict:
        """
        Convert to sync-compatible dict (matches ActivityDTO)
        This is the official payload format for sync operations.
        """
        return {
            "uuid": self.uuid,
            "server_id": self.id,
            "project_id": self.project_id,
            "front_id": self.front_id,
            "pk_start": self.pk_start,
            "pk_end": self.pk_end,
            "execution_state": self.execution_state,
            "assigned_to_user_id": self.assigned_to_user_id,
            "created_by_user_id": self.created_by_user_id,
            "catalog_version_id": self.catalog_version_id,
            "activity_type_code": self.activity_type_code,
            "latitude": self.latitude,
            "longitude": self.longitude,
            "title": self.title,
            "description": self.description,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "deleted_at": self.deleted_at.isoformat() if self.deleted_at else None,
            "sync_version": self.sync_version,
        }
