"""Event model - Incidents reported from the field."""
import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    String,
    Integer,
    DateTime,
    Text,
    ForeignKey,
    CheckConstraint,
    Index,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.models.base import BaseModel


class EventSeverity(str, enum.Enum):
    """Severity levels for reported events."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


VALID_SEVERITIES = [s.value for s in EventSeverity]


class Event(BaseModel):
    """
    Event model — field incident reporting.

    Sync contract (identical to Activity):
    - uuid: generated by mobile, immutable, used for idempotency
    - server_id: backend autoincrement (id field)
    - sync_version: monotonic increment for pull sync cursor
    - deleted_at: soft delete
    """
    __tablename__ = "events"

    # ── Identity ─────────────────────────────────────────────
    id = Column(Integer, primary_key=True, autoincrement=True)  # server_id
    uuid = Column(UUID(as_uuid=True), unique=True, nullable=False, index=True)

    # ── Sync ─────────────────────────────────────────────────
    sync_version = Column(Integer, nullable=False, default=0, index=True)
    deleted_at = Column(DateTime, nullable=True, index=True)

    # ── Territorial context ───────────────────────────────────
    project_id = Column(String(10), ForeignKey("projects.id"), nullable=False, index=True)

    # ── Event type (catalog-driven) ───────────────────────────
    event_type_code = Column(String(50), nullable=False)  # e.g., "DERRAME", "CAIDA"

    # ── Event metadata ────────────────────────────────────────
    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)
    severity = Column(String(10), nullable=False, default=EventSeverity.MEDIUM.value, index=True)

    # Location at time of incident (PK in meters + GPS)
    location_pk_meters = Column(Integer, nullable=True, index=True)
    latitude = Column(String(20), nullable=True)
    longitude = Column(String(20), nullable=True)

    # ── Timestamps ───────────────────────────────────────────
    occurred_at = Column(DateTime(timezone=True), nullable=False)   # When the incident happened
    resolved_at = Column(DateTime(timezone=True), nullable=True)     # When resolved (nullable)

    # ── Users ────────────────────────────────────────────────
    reported_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    assigned_to_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    # ── Form fields (dynamic form answers, JSON blob) ─────────
    form_fields_json = Column(Text, nullable=True)  # JSON string of {field_key: value}

    # ── Relationships ─────────────────────────────────────────
    project = relationship("Project", foreign_keys=[project_id])
    reported_by = relationship("User", foreign_keys=[reported_by_user_id])
    assigned_to = relationship("User", foreign_keys=[assigned_to_user_id])

    # ── Constraints ───────────────────────────────────────────
    __table_args__ = (
        CheckConstraint(
            f"severity IN ('{EventSeverity.LOW.value}', '{EventSeverity.MEDIUM.value}', "
            f"'{EventSeverity.HIGH.value}', '{EventSeverity.CRITICAL.value}')",
            name="check_event_severity",
        ),
        Index("idx_event_sync", "sync_version", "updated_at"),
        Index("idx_event_project_severity", "project_id", "severity"),
    )

    def __repr__(self):
        return f"<Event {self.uuid} [{self.severity}] {self.event_type_code}>"

    def increment_sync_version(self):
        self.sync_version += 1

    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def soft_delete(self):
        self.deleted_at = datetime.now(timezone.utc)
        self.increment_sync_version()

    @property
    def is_resolved(self) -> bool:
        return self.resolved_at is not None
