"""add_catalog_models

Revision ID: 894874841371
Revises: 2943c465af13
Create Date: 2026-02-17 19:07:04.763889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894874841371'
down_revision = '2943c465af13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=10), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DEPRECATED', name='catalogstatus'), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_by_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_project_version')
    )
    op.create_index('idx_catalog_project_status', 'catalog_versions', ['project_id', 'status'], unique=False)
    op.create_table('cat_activity_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'code', name='uq_activity_type_code')
    )
    op.create_index('idx_activity_type_version', 'cat_activity_types', ['version_id'], unique=False)
    op.create_table('cat_event_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_create_activity', sa.Boolean(), nullable=False),
    sa.Column('requires_immediate_response', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'code', name='uq_event_type_code')
    )
    op.create_index('idx_event_type_version', 'cat_event_types', ['version_id'], unique=False)
    op.create_table('cat_evidence_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('ACTIVITY', 'EVENT', name='entitytype'), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('min_photos', sa.Integer(), nullable=False),
    sa.Column('max_photos', sa.Integer(), nullable=True),
    sa.Column('requires_gps', sa.Boolean(), nullable=False),
    sa.Column('requires_signature', sa.Boolean(), nullable=False),
    sa.Column('allowed_file_types', sa.JSON(), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'entity_type', 'type_id', name='uq_evidence_rule_type')
    )
    op.create_index('idx_evidence_rule_version', 'cat_evidence_rules', ['version_id'], unique=False)
    op.create_table('cat_form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('ACTIVITY', 'EVENT', name='entitytype'), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('widget', sa.Enum('TEXT', 'NUMBER', 'DATE', 'TIME', 'DATETIME', 'TEXTAREA', 'SELECT', 'MULTISELECT', 'RADIO', 'CHECKBOX', 'GPS', 'SIGNATURE', 'FILE', 'PHOTO', name='widgettype'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('validation_regex', sa.String(length=500), nullable=True),
    sa.Column('validation_message', sa.String(length=255), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('visible_when', sa.JSON(), nullable=True),
    sa.Column('required_when', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'entity_type', 'type_id', 'key', name='uq_form_field_key')
    )
    op.create_index('idx_form_field_version_entity', 'cat_form_fields', ['version_id', 'entity_type', 'type_id'], unique=False)
    op.create_table('cat_workflow_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('ACTIVITY', 'EVENT', name='entitytype'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'entity_type', 'code', name='uq_workflow_state_code')
    )
    op.create_index('idx_workflow_state_version_entity', 'cat_workflow_states', ['version_id', 'entity_type'], unique=False)
    op.create_table('cat_checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('activity_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['cat_activity_types.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checklist_activity', 'cat_checklist_templates', ['activity_type_id'], unique=False)
    op.create_index('idx_checklist_version', 'cat_checklist_templates', ['version_id'], unique=False)
    op.create_table('cat_workflow_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('from_state_id', sa.UUID(), nullable=False),
    sa.Column('to_state_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=True),
    sa.Column('required_permissions', sa.JSON(), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('confirm_message', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['cat_workflow_states.id'], ),
    sa.ForeignKeyConstraint(['to_state_id'], ['cat_workflow_states.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_transition_states', 'cat_workflow_transitions', ['from_state_id', 'to_state_id'], unique=False)
    op.create_index('idx_workflow_transition_version', 'cat_workflow_transitions', ['version_id'], unique=False)
    op.alter_column('fronts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('fronts', 'responsible_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('locations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_role_scopes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_role_scopes', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_role_scopes', 'front_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_role_scopes', 'location_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_role_scopes', 'assigned_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_role_scopes', 'assigned_by_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('user_role_scopes', 'location_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('user_role_scopes', 'front_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('user_role_scopes', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_role_scopes', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('locations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('fronts', 'responsible_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('fronts', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index('idx_workflow_transition_version', table_name='cat_workflow_transitions')
    op.drop_index('idx_workflow_transition_states', table_name='cat_workflow_transitions')
    op.drop_table('cat_workflow_transitions')
    op.drop_index('idx_checklist_version', table_name='cat_checklist_templates')
    op.drop_index('idx_checklist_activity', table_name='cat_checklist_templates')
    op.drop_table('cat_checklist_templates')
    op.drop_index('idx_workflow_state_version_entity', table_name='cat_workflow_states')
    op.drop_table('cat_workflow_states')
    op.drop_index('idx_form_field_version_entity', table_name='cat_form_fields')
    op.drop_table('cat_form_fields')
    op.drop_index('idx_evidence_rule_version', table_name='cat_evidence_rules')
    op.drop_table('cat_evidence_rules')
    op.drop_index('idx_event_type_version', table_name='cat_event_types')
    op.drop_table('cat_event_types')
    op.drop_index('idx_activity_type_version', table_name='cat_activity_types')
    op.drop_table('cat_activity_types')
    op.drop_index('idx_catalog_project_status', table_name='catalog_versions')
    op.drop_table('catalog_versions')
    # ### end Alembic commands ###
