"""Activity schemas - Official v1 Contract"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


VALID_EXECUTION_STATES = ["PENDIENTE", "EN_CURSO", "REVISION_PENDIENTE", "COMPLETADA", "CANCELED"]

VALID_OPERATIONAL_STATES = ["PENDIENTE", "EN_CURSO", "POR_COMPLETAR", "BLOQUEADA", "CANCELADA"]
VALID_SYNC_STATES = ["LOCAL_ONLY", "READY_TO_SYNC", "SYNC_IN_PROGRESS", "SYNCED", "SYNC_ERROR"]
VALID_REVIEW_STATES = ["NOT_APPLICABLE", "PENDING_REVIEW", "CHANGES_REQUIRED", "APPROVED", "REJECTED"]


def infer_sync_state(
    sync_state: str | None,
    *,
    has_local_changes: bool | None = None,
    has_sync_error: bool | None = None,
    sync_in_progress: bool | None = None,
) -> str:
    state = str(sync_state or "").strip().upper()
    if state in VALID_SYNC_STATES:
        return state

    if has_sync_error:
        return "SYNC_ERROR"
    if sync_in_progress:
        return "SYNC_IN_PROGRESS"
    if has_local_changes:
        return "READY_TO_SYNC"

    if state in {"ERROR", "FAILED", "FAILURE"}:
        return "SYNC_ERROR"
    if state in {"SYNCING", "IN_PROGRESS"}:
        return "SYNC_IN_PROGRESS"
    if state in {"PENDING", "QUEUED", "READY", "LOCAL"}:
        return "READY_TO_SYNC"
    return "SYNCED"


def infer_review_state(execution_state: str | None, review_decision: str | None) -> str:
    decision = str(review_decision or "").strip().upper()
    if decision in {"APPROVE", "APPROVE_EXCEPTION"}:
        return "APPROVED"
    if decision == "REJECT":
        return "REJECTED"
    if decision in {"CHANGES_REQUIRED", "REQUEST_CHANGES", "REQUIRES_CHANGES"}:
        return "CHANGES_REQUIRED"
    if str(execution_state or "").upper() in {"REVISION_PENDIENTE", "COMPLETADA"}:
        return "PENDING_REVIEW"
    return "NOT_APPLICABLE"


def infer_operational_state(execution_state: str | None) -> str:
    state = str(execution_state or "").strip().upper()
    if state == "PENDIENTE":
        return "PENDIENTE"
    if state == "EN_CURSO":
        return "EN_CURSO"
    if state == "CANCELED":
        return "CANCELADA"
    if state in {"REVISION_PENDIENTE", "COMPLETADA"}:
        return "POR_COMPLETAR"
    return "PENDIENTE"


def infer_next_action(
    operational_state: str,
    sync_state: str,
    review_state: str,
) -> str:
    if review_state == "CHANGES_REQUIRED":
        return "CORREGIR_Y_REENVIAR"
    if review_state == "PENDING_REVIEW":
        return "ESPERAR_DECISION_COORDINACION"
    if review_state == "APPROVED":
        return "CERRADA_APROBADA"
    if review_state == "REJECTED":
        return "CERRADA_RECHAZADA"
    if sync_state == "SYNC_ERROR":
        return "REVISAR_ERROR_SYNC"
    if sync_state == "READY_TO_SYNC":
        return "SINCRONIZAR_PENDIENTE"
    if operational_state == "PENDIENTE":
        return "INICIAR_ACTIVIDAD"
    if operational_state == "EN_CURSO":
        return "TERMINAR_ACTIVIDAD"
    if operational_state == "POR_COMPLETAR":
        return "COMPLETAR_WIZARD"
    if operational_state == "CANCELADA":
        return "CERRADA_CANCELADA"
    return "SIN_ACCION"


def build_canonical_flow_projection(
    *,
    execution_state: str | None,
    review_decision: str | None,
    sync_state: str | None,
    has_local_changes: bool | None = None,
    has_sync_error: bool | None = None,
    sync_in_progress: bool | None = None,
) -> dict[str, str]:
    operational_state = infer_operational_state(execution_state)
    normalized_sync_state = infer_sync_state(
        sync_state,
        has_local_changes=has_local_changes,
        has_sync_error=has_sync_error,
        sync_in_progress=sync_in_progress,
    )
    review_state = infer_review_state(execution_state, review_decision)
    next_action = infer_next_action(
        operational_state=operational_state,
        sync_state=normalized_sync_state,
        review_state=review_state,
    )
    return {
        "operational_state": operational_state,
        "sync_state": normalized_sync_state,
        "review_state": review_state,
        "next_action": next_action,
    }


class ActivityBase(BaseModel):
    """Base activity fields"""
    uuid: UUID = Field(..., description="UUID generated by mobile, immutable, unique global")
    project_id: str = Field(..., description="Project ID reference")
    front_id: UUID | None = Field(None, description="Front/Segment ID (UUID), nullable for general activities")
    pk_start: int = Field(..., description="PK start in METERS (e.g., km 142+000 → 142000)")
    pk_end: int | None = Field(None, description="PK end in METERS, nullable for point activities")
    execution_state: str = Field("PENDIENTE", description="PENDIENTE | EN_CURSO | REVISION_PENDIENTE | COMPLETADA")
    assigned_to_user_id: UUID | None = Field(None, description="User ID (UUID) assigned to this activity")
    catalog_version_id: UUID = Field(..., description="Catalog version ID (UUID) this activity uses")
    activity_type_code: str = Field(..., description="Activity type code from catalog (e.g., INSP_CIVIL)")
    latitude: str | None = Field(None, description="Latitude in decimal degrees")
    longitude: str | None = Field(None, description="Longitude in decimal degrees")
    title: str | None = Field(None, max_length=200, description="Activity title")
    description: str | None = Field(None, description="Activity description")
    
    @field_validator("execution_state")
    @classmethod
    def validate_execution_state(cls, value: str) -> str:
        """Validate allowed execution states."""
        if value not in VALID_EXECUTION_STATES:
            raise ValueError(f"execution_state must be one of: {VALID_EXECUTION_STATES}")
        return value

    @model_validator(mode="after")
    def validate_pk_range(self):
        """Ensure pk_end is not less than pk_start when provided."""
        if self.pk_end is not None and self.pk_end < self.pk_start:
            raise ValueError("pk_end must be >= pk_start")
        return self


class ActivityCreate(ActivityBase):
    """
    Schema for creating activity (from mobile push)
    Mobile generates uuid, server assigns server_id
    """
    created_by_user_id: UUID = Field(..., description="User ID (UUID) who created this activity")
    # Optional: mobile can send provisional timestamps
    created_at: datetime | None = None
    updated_at: datetime | None = None


class ActivityUpdate(BaseModel):
    """Schema for updating activity"""
    front_id: UUID | None = None
    pk_start: int | None = None
    pk_end: int | None = None
    execution_state: str | None = None
    assigned_to_user_id: UUID | None = None
    activity_type_code: str | None = None
    latitude: str | None = None
    longitude: str | None = None
    title: str | None = None
    description: str | None = None
    
    @field_validator("execution_state")
    @classmethod
    def validate_execution_state(cls, value: str | None) -> str | None:
        """Validate optional execution state updates."""
        if value is not None and value not in VALID_EXECUTION_STATES:
            raise ValueError(f"execution_state must be one of: {VALID_EXECUTION_STATES}")
        return value


class ActivityDTO(BaseModel):
    """
    Official Activity DTO v1 - Sync Contract
    This is the CANONICAL format for sync operations
    MUST match between backend and mobile
    """
    uuid: UUID
    server_id: int | None = Field(None, alias="id", serialization_alias="server_id", description="Autoincrement ID from server, null before first sync")
    project_id: str
    front_id: UUID | None = None
    pk_start: int
    pk_end: int | None = None
    execution_state: str
    review_decision: str | None = Field(None, description="APPROVE | REJECT")
    review_reject_reason_code: str | None = Field(
        None,
        description="Machine-readable reject reason code for corrections",
    )
    review_comment: str | None = Field(
        None,
        description="Human-readable coordinator comment explaining what to correct",
    )
    assigned_to_user_id: UUID | None = None
    assigned_to_user_name: str | None = None
    created_by_user_id: UUID
    catalog_version_id: UUID | str | None = None
    activity_type_code: str
    latitude: str | None = None
    longitude: str | None = None
    title: str | None = None
    description: str | None = None
    wizard_payload: dict[str, Any] | None = Field(
        None,
        description="Structured wizard payload with classification/location metadata",
    )
    flags: dict[str, bool] = Field(default_factory=lambda: {
        "gps_mismatch": False,
        "catalog_changed": False,
    })
    operational_state: str = Field("PENDIENTE", description="PENDIENTE | EN_CURSO | POR_COMPLETAR | BLOQUEADA | CANCELADA")
    sync_state: str = Field("SYNCED", description="LOCAL_ONLY | READY_TO_SYNC | SYNC_IN_PROGRESS | SYNCED | SYNC_ERROR")
    review_state: str = Field("NOT_APPLICABLE", description="NOT_APPLICABLE | PENDING_REVIEW | CHANGES_REQUIRED | APPROVED | REJECTED")
    next_action: str = Field("SIN_ACCION", description="Normalized next action for clients")
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    sync_version: int = Field(..., description="Monotonic increment for pull sync cursor")

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    @model_validator(mode='after')
    def _resolve_assigned_user_name(self) -> 'ActivityDTO':
        # When built from ORM via from_attributes, try to resolve the name
        # from the `assigned_to` relationship if not already set.
        if self.assigned_to_user_name is None and self.assigned_to_user_id is not None:
            # Pydantic populates __pydantic_fields_set__; the ORM object may
            # expose `.assigned_to.full_name` if the relationship was loaded.
            pass  # resolved via model_post_init below
        return self

    @model_validator(mode="after")
    def _hydrate_canonical_flow_projection(self) -> 'ActivityDTO':
        projection = build_canonical_flow_projection(
            execution_state=self.execution_state,
            review_decision=self.review_decision,
            sync_state=self.sync_state,
        )
        self.operational_state = projection["operational_state"]
        self.sync_state = projection["sync_state"]
        self.review_state = projection["review_state"]
        self.next_action = projection["next_action"]
        return self

    @classmethod
    def from_orm_activity(cls, activity: Any) -> 'ActivityDTO':
        """Build DTO from ORM Activity, resolving assigned_to name if loaded."""
        obj = cls.model_validate(activity)
        if obj.assigned_to_user_name is None and activity.assigned_to is not None:
            try:
                obj = obj.model_copy(update={'assigned_to_user_name': activity.assigned_to.full_name})
            except Exception:
                pass
        return obj


class ActivityListResponse(BaseModel):
    """Response for list activities endpoint"""
    items: list[ActivityDTO]
    total: int
    page: int
    page_size: int
    has_next: bool


class ActivitySyncPushRequest(BaseModel):
    """Request for pushing activities from mobile"""
    activities: list[ActivityCreate]


class ActivitySyncPushResponse(BaseModel):
    """Response after push sync"""
    accepted: int
    rejected: int
    conflicts: list[dict]  # List of activities with conflicts


class ActivitySyncPullResponse(BaseModel):
    """Response for pull sync"""
    activities: list[ActivityDTO]
    latest_sync_version: int
    has_more: bool


class ActivityFlagsUpdate(BaseModel):
    """Partial update for structured review flags. Omitted fields are left unchanged."""
    gps_mismatch: bool | None = None
    catalog_changed: bool | None = None


class ActivityTimelineItem(BaseModel):
    """Single audit timeline row for an activity."""
    at: datetime
    actor: str | None = None
    action: str
    details: dict[str, Any] | None = None
