"""Activity schemas - Official v1 Contract"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


VALID_EXECUTION_STATES = ["PENDIENTE", "EN_CURSO", "REVISION_PENDIENTE", "COMPLETADA"]


class ActivityBase(BaseModel):
    """Base activity fields"""
    uuid: UUID = Field(..., description="UUID generated by mobile, immutable, unique global")
    project_id: str = Field(..., description="Project ID reference")
    front_id: UUID | None = Field(None, description="Front/Segment ID (UUID), nullable for general activities")
    pk_start: int = Field(..., description="PK start in METERS (e.g., km 142+000 → 142000)")
    pk_end: int | None = Field(None, description="PK end in METERS, nullable for point activities")
    execution_state: str = Field("PENDIENTE", description="PENDIENTE | EN_CURSO | REVISION_PENDIENTE | COMPLETADA")
    assigned_to_user_id: UUID | None = Field(None, description="User ID (UUID) assigned to this activity")
    catalog_version_id: UUID = Field(..., description="Catalog version ID (UUID) this activity uses")
    activity_type_code: str = Field(..., description="Activity type code from catalog (e.g., INSP_CIVIL)")
    latitude: str | None = Field(None, description="Latitude in decimal degrees")
    longitude: str | None = Field(None, description="Longitude in decimal degrees")
    title: str | None = Field(None, max_length=200, description="Activity title")
    description: str | None = Field(None, description="Activity description")
    
    @field_validator("execution_state")
    @classmethod
    def validate_execution_state(cls, value: str) -> str:
        """Validate allowed execution states."""
        if value not in VALID_EXECUTION_STATES:
            raise ValueError(f"execution_state must be one of: {VALID_EXECUTION_STATES}")
        return value

    @model_validator(mode="after")
    def validate_pk_range(self):
        """Ensure pk_end is not less than pk_start when provided."""
        if self.pk_end is not None and self.pk_end < self.pk_start:
            raise ValueError("pk_end must be >= pk_start")
        return self


class ActivityCreate(ActivityBase):
    """
    Schema for creating activity (from mobile push)
    Mobile generates uuid, server assigns server_id
    """
    created_by_user_id: UUID = Field(..., description="User ID (UUID) who created this activity")
    # Optional: mobile can send provisional timestamps
    created_at: datetime | None = None
    updated_at: datetime | None = None


class ActivityUpdate(BaseModel):
    """Schema for updating activity"""
    front_id: UUID | None = None
    pk_start: int | None = None
    pk_end: int | None = None
    execution_state: str | None = None
    assigned_to_user_id: UUID | None = None
    activity_type_code: str | None = None
    latitude: str | None = None
    longitude: str | None = None
    title: str | None = None
    description: str | None = None
    
    @field_validator("execution_state")
    @classmethod
    def validate_execution_state(cls, value: str | None) -> str | None:
        """Validate optional execution state updates."""
        if value is not None and value not in VALID_EXECUTION_STATES:
            raise ValueError(f"execution_state must be one of: {VALID_EXECUTION_STATES}")
        return value


class ActivityDTO(BaseModel):
    """
    Official Activity DTO v1 - Sync Contract
    This is the CANONICAL format for sync operations
    MUST match between backend and mobile
    """
    uuid: UUID
    server_id: int | None = Field(None, alias="id", serialization_alias="server_id", description="Autoincrement ID from server, null before first sync")
    project_id: str
    front_id: UUID | None = None
    pk_start: int
    pk_end: int | None = None
    execution_state: str
    assigned_to_user_id: UUID | None = None
    created_by_user_id: UUID
    catalog_version_id: UUID
    activity_type_code: str
    latitude: str | None = None
    longitude: str | None = None
    title: str | None = None
    description: str | None = None
    flags: dict[str, bool] = Field(default_factory=lambda: {
        "gps_mismatch": False,
        "catalog_changed": False,
    })
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    sync_version: int = Field(..., description="Monotonic increment for pull sync cursor")
    
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


class ActivityListResponse(BaseModel):
    """Response for list activities endpoint"""
    items: list[ActivityDTO]
    total: int
    page: int
    page_size: int
    has_next: bool


class ActivitySyncPushRequest(BaseModel):
    """Request for pushing activities from mobile"""
    activities: list[ActivityCreate]


class ActivitySyncPushResponse(BaseModel):
    """Response after push sync"""
    accepted: int
    rejected: int
    conflicts: list[dict]  # List of activities with conflicts


class ActivitySyncPullResponse(BaseModel):
    """Response for pull sync"""
    activities: list[ActivityDTO]
    latest_sync_version: int
    has_more: bool


class ActivityFlagsUpdate(BaseModel):
    """Partial update for structured review flags. Omitted fields are left unchanged."""
    gps_mismatch: bool | None = None
    catalog_changed: bool | None = None


class ActivityTimelineItem(BaseModel):
    """Single audit timeline row for an activity."""
    at: datetime
    actor: str | None = None
    action: str
    details: dict[str, Any] | None = None
