"""Event schemas — field incident DTOs."""

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


VALID_SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]


class EventBase(BaseModel):
    """Base fields shared by create/update schemas."""
    event_type_code: str = Field(..., description="Event type code from catalog")
    title: str = Field(..., min_length=1, max_length=200, description="Short description of the incident")
    description: str | None = Field(None, description="Extended description")
    severity: str = Field("MEDIUM", description="LOW | MEDIUM | HIGH | CRITICAL")
    location_pk_meters: int | None = Field(None, description="PK location in METERS")
    latitude: str | None = Field(None, description="Latitude in decimal degrees")
    longitude: str | None = Field(None, description="Longitude in decimal degrees")
    occurred_at: datetime = Field(..., description="UTC datetime when the incident occurred")
    assigned_to_user_id: UUID | None = Field(None, description="User assigned to resolve")
    form_fields_json: str | None = Field(None, description="JSON of dynamic form answers")

    @field_validator("severity")
    @classmethod
    def validate_severity(cls, value: str) -> str:
        if value not in VALID_SEVERITIES:
            raise ValueError(f"severity must be one of: {VALID_SEVERITIES}")
        return value


class EventCreate(EventBase):
    """Schema for creating an event (from mobile push)."""
    uuid: UUID = Field(..., description="UUID generated by mobile, immutable")
    project_id: str = Field(..., description="Project ID reference")
    reported_by_user_id: UUID = Field(..., description="User UUID who reported the event")
    # Mobile timestamps (ignored by server, server sets its own)
    created_at: datetime | None = None
    updated_at: datetime | None = None
    sync_version: int | None = None
    deleted_at: datetime | None = None


class EventUpdate(BaseModel):
    """Schema for updating a field incident."""
    title: str | None = Field(None, max_length=200)
    description: str | None = None
    severity: str | None = None
    location_pk_meters: int | None = None
    latitude: str | None = None
    longitude: str | None = None
    occurred_at: datetime | None = None
    resolved_at: datetime | None = Field(None, description="Set to mark as resolved")
    assigned_to_user_id: UUID | None = None
    form_fields_json: str | None = None

    @field_validator("severity")
    @classmethod
    def validate_severity(cls, value: str | None) -> str | None:
        if value is not None and value not in VALID_SEVERITIES:
            raise ValueError(f"severity must be one of: {VALID_SEVERITIES}")
        return value


class EventDTO(BaseModel):
    """
    Official Event DTO — sync contract between backend and mobile.
    Mirrors ActivityDTO structure for consistency.
    """
    uuid: UUID
    server_id: int | None = Field(None, alias="id", serialization_alias="server_id")
    project_id: str
    event_type_code: str
    title: str
    description: str | None = None
    severity: str
    location_pk_meters: int | None = None
    latitude: str | None = None
    longitude: str | None = None
    occurred_at: datetime
    resolved_at: datetime | None = None
    reported_by_user_id: UUID
    assigned_to_user_id: UUID | None = None
    form_fields_json: str | None = None
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
    sync_version: int

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


class EventListResponse(BaseModel):
    """Response for list events endpoint."""
    items: list[EventDTO]
    total: int
    page: int
    page_size: int
    has_next: bool
