"""Sync schemas for pull/push operations"""

from datetime import datetime
from typing import Literal, Union
from uuid import UUID

from pydantic import BaseModel, Field, field_validator, model_validator

from app.schemas.activity import ActivityDTO, VALID_EXECUTION_STATES


class SyncPullRequest(BaseModel):
    """Request schema for sync pull operation"""
    project_id: str = Field(..., description="Project ID to sync activities for")
    since_version: int = Field(0, ge=0, description="Last sync_version client has; server returns activities with sync_version > this")
    after_uuid: UUID | None = Field(
        None,
        description="Optional tie-breaker for pagination when multiple rows share since_version",
    )
    until_version: int | None = Field(None, ge=0, description="Optional upper bound for sync_version; if provided, returns activities with sync_version <= this")
    limit: int = Field(500, ge=1, le=1000, description="Maximum number of activities to return")


class SyncPullResponse(BaseModel):
    """Response schema for sync pull operation"""
    current_version: int = Field(..., description="Maximum sync_version in returned activities; client should use this for next pull")
    has_more: bool = Field(False, description="Whether there are more activities available for the same snapshot window")
    next_since_version: int | None = Field(
        None,
        description="Cursor value to use for next pull page when has_more is true",
    )
    next_after_uuid: UUID | None = Field(
        None,
        description="Tie-breaker UUID cursor to use with next_since_version",
    )
    activities: list[ActivityDTO] = Field(default_factory=list, description="List of activities updated since since_version")


class SyncPushActivityItem(BaseModel):
    """Activity item for push sync from client"""
    uuid: UUID = Field(..., description="UUID generated by mobile, immutable")
    server_id: int | None = Field(None, description="Server ID, optional/nullable for new activities")
    project_id: str = Field(..., description="Project ID reference")
    front_id: UUID | None = Field(None, description="Front/Segment ID (UUID), nullable")
    pk_start: int = Field(..., description="PK start in METERS")
    pk_end: int | None = Field(None, description="PK end in METERS, nullable")
    execution_state: str = Field(..., description="PENDIENTE | EN_CURSO | REVISION_PENDIENTE | COMPLETADA")
    assigned_to_user_id: UUID | None = Field(None, description="User ID (UUID) assigned")
    created_by_user_id: UUID = Field(..., description="User ID (UUID) who created")
    catalog_version_id: Union[UUID, str] = Field(..., description="Catalog version ID (UUID or semantic string such as 'tmq-v1.0.0' for Firestore mode)")

    @field_validator("catalog_version_id", mode="before")
    @classmethod
    def normalize_catalog_version_id(cls, v: object) -> Union[UUID, str]:
        if isinstance(v, UUID):
            return v
        if isinstance(v, str):
            stripped = v.strip()
            if not stripped:
                raise ValueError("catalog_version_id must not be empty")
            try:
                return UUID(stripped)
            except ValueError:
                return stripped
        raise ValueError("catalog_version_id must be a UUID or non-empty string")
    activity_type_code: str = Field(..., description="Activity type code from catalog")
    latitude: str | None = Field(None, description="Latitude in decimal degrees")
    longitude: str | None = Field(None, description="Longitude in decimal degrees")
    title: str | None = Field(None, description="Activity title")
    description: str | None = Field(None, description="Activity description")
    wizard_payload: dict[str, object] | None = Field(
        None,
        description="Structured wizard payload with classification/location metadata",
    )
    deleted_at: datetime | None = Field(None, description="Deletion timestamp if soft-deleted")
    # Client-provided timestamps and sync_version are ignored by server
    created_at: datetime | None = None
    updated_at: datetime | None = None
    sync_version: int | None = None

    @field_validator("execution_state")
    @classmethod
    def validate_execution_state(cls, value: str) -> str:
        if value not in VALID_EXECUTION_STATES:
            raise ValueError(f"execution_state must be one of: {VALID_EXECUTION_STATES}")
        return value

    @model_validator(mode="after")
    def validate_pk_range(self):
        if self.pk_end is not None and self.pk_end < self.pk_start:
            raise ValueError("pk_end must be >= pk_start")
        return self


class SyncPushRequest(BaseModel):
    """Request schema for sync push operation"""
    project_id: str = Field(..., description="Project ID for activities being pushed")
    force_override: bool = Field(
        False,
        description="If true, server applies incoming changes even when stale/conflicting",
    )
    activities: list[SyncPushActivityItem] = Field(..., description="List of activities to push")


class SyncPushResultItem(BaseModel):
    """Result for a single pushed activity"""
    uuid: UUID = Field(..., description="UUID of the activity")
    status: Literal["CREATED", "UPDATED", "UNCHANGED", "CONFLICT", "INVALID"] = Field(..., description="Result status")
    server_id: int | None = Field(None, description="Server-assigned ID when available")
    sync_version: int = Field(..., description="Current sync_version after operation")
    error_code: str | None = Field(None, description="Machine-readable validation error code")
    message: str | None = Field(None, description="Validation/conflict message")
    retryable: bool | None = Field(None, description="Whether client can retry automatically")
    suggested_action: str | None = Field(None, description="Suggested next action for UX guidance")


class SyncPushResponse(BaseModel):
    """Response schema for sync push operation"""
    results: list[SyncPushResultItem] = Field(..., description="Per-activity push results")
